version: "3.9"

services:
  example:
    build:
      context: ..
      dockerfile: docker/example.Dockerfile
      tags:
        - latest
    image: "ros-otel-example:latest"
    container_name: ros-otel-example
    environment:
      - OTLP_ENDPOINT=host.docker.internal:4317
      - ROS_LOG_DIR=/workspace/docker_workspace/logs/ros
    extra_hosts:
      - "host.docker.internal:host-gateway"
    tty: true
    network_mode: bridge
    ports:
      - "8765:8765"
    volumes:
      - ../logs/ros:/workspace/docker_workspace/logs/ros:rw

  lichtblick:
    image: ghcr.io/lichtblick-suite/lichtblick:1.14.0
    container_name: lichtblick
    depends_on:
      - example
    ports:
      - "4444:8080"
    tty: true
